#!/usr/bin/python3

import rosbag
import argparse

from hemisphere_v500_msgs.msg import StampedString

def parse_gpgga(msg):
    tokens = msg.split(',')

    latStr = tokens[2]
    lat = float(latStr[:2]) + float(latStr[2:]) / 60.0
    if 'S' in tokens[3]:
        lat = -lat

    lonStr = tokens[4]
    lon = float(lonStr[:3]) + float(lonStr[3:]) / 60.0
    if 'E' in tokens[5]:
        lon = -lon

    alt = float(tokens[9])
    return lat,lon,alt

def parse_psat(msg):
    tokens = msg.split(',')

    return float(tokens[3]), float(tokens[4]), float(tokens[5])

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        prog='gnss_bag_to_csv',
        description=('Reads the NMEA StampedString messages in a ROS bag '
                     'generated by the hemisphere_v500 ROS node and exports a '
                     '.csv file containing gpsTime,lat,lon,alt,heading,pitch,roll'))
    parser.add_argument('bag_path', type=str,
                        help='path to rosbag file')
    parser.add_argument('-o', '--output', type=str, default='output.csv',
                        help='path to rosbag file')
    args = parser.parse_args()
    
    bag = rosbag.Bag(args.bag_path)

    msgs = {}
    for topic,msg,t in bag.read_messages(topics=['/gnss_v500/nmea']):
        tokens = msg.data.split(',')
        if tokens[0] == "$GPGGA":
            stamp = tokens[1]
        elif tokens[0] == "$PSAT":
            stamp = tokens[2]
        
        if stamp not in msgs.keys():
            msgs[stamp] = {}
        msgs[stamp][tokens[0]] = msg.data
    
    with open(args.output,'w') as f:
        f.write("# gpsTime,lat,lon,alt,heading,pitch,roll\r\n")
        for stamp, msgs in msgs.items():
            if len(msgs) != 2:
                continue
        
            lat,lon,alt        = parse_gpgga(msgs["$GPGGA"])
            heading,pitch,roll = parse_psat(msgs["$PSAT"])
    
            f.write(  str(stamp)   + ','
                    + str(lat)     + ','
                    + str(lon)     + ','
                    + str(alt)     + ','
                    + str(heading) + ','
                    + str(pitch)   + ','
                    + str(roll)    + '\r\n')


